import { Profile } from "../types/types";

export const profiles: Profile[] = [
  {
    fullname: "Jane Doe",
    progress: 60,
    status: "In Progress",
    language: "Arabic",
    lastupdated: "3 days ago",
    gender: "Female",
    location: "Downtown",
    assignedStaff: "John Smith",
  },
  {
    fullname: "John Smith",
    progress: 100,
    status: "Completed, Needs Review",
    language: "Ukrainian",
    lastupdated: "5 days ago",
    gender: "Male",
    location: "West End",
    assignedStaff: "Mike",
  },
  {
    fullname: "Ahmed Saleh",
    progress: 0,
    status: "Not Started, Flagged",
    language: "Arabic",
    lastupdated: "2 weeks ago",
    gender: "Male",
    location: "East Side",
    assignedStaff: "Sarah",
  },
  {
    fullname: "Alsha Khan",
    progress: 45,
    status: "Delayed",
    language: "Ukrainian",
    lastupdated: "2 weeks ago",
    gender: "Female",
    location: "North Point",
    assignedStaff: "David",
  },
  {
    fullname: "Farah Ali",
    progress: 20,
    status: "In Progress",
    language: "Arabic",
    lastupdated: "1 month ago",
    gender: "Female",
    location: "South Park",
    assignedStaff: "Aisha",
  },
  {
    fullname: "Ishaan Patel",
    progress: 0,
    status: "Not Started, Delayed",
    language: "Ukrainian",
    lastupdated: "2 months ago",
    gender: "Male",
    location: "Central City",
    assignedStaff: "Priya",
  },
  {
    fullname: "Ehsaan Qureshi",
    progress: 0,
    status: "Not Started, Othelayed",
    language: "Hindi",
    lastupdated: "2 months ago",
    gender: "Male",
    location: "Old Town",
    assignedStaff: "Ravi",
  },
];

